name: Publish PPA
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Setup GIT config
        run: |
          git config user.name "A-SIT PPA Bot"
          git config user.email "software@egiz.gv.at"

      - name: Import GPG Signing key
        run: |
          echo -e "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
        env:
          GPG_SIGNING_KEY: ${{ secrets.ASIT_PPA_NIGHTLY_GPG_SIGNING_KEY }}

      - name: Update, Re-Sign, and Publish PPA
        run: |
          bash update.sh
          git push
          
      - name: Cleanup GPG
        run: rm -rf ~/.gnupg
